language: android
android:
  components:
    - build-tools-24.0.1
    - android-24
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/